apiVersion: v1
kind: Service
metadata:
  name: {{ include "bins.fullname" . }}-website
spec:
  type: {{ .Values.website.service.type }}
  ports:
    - port: {{ .Values.website.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "bins.fullname" . }}-website
