compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - code: YN0013
    level: discard

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x64
    - current
  libc:
    - musl
    - current
  os:
    - linux
    - current

yarnPath: .yarn/releases/yarn-4.0.0.cjs
