logFilters:
  - code: YN0013
    level: discard

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.3.0.cjs

supportedArchitectures:
  libc:
    - "musl"
    - "current"
  os:
    - "linux"
    - "current"
  cpu:
    - "x64"
    - "current"