FROM node:19-alpine as build
ARG APP_NAME

WORKDIR /base
COPY . ./
RUN yarn install --frozen-lockfile
RUN cd packages/$APP_NAME && yarn build

FROM nginx:stable-alpine
ARG APP_NAME
COPY --from=build /base/packages/$APP_NAME/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]