version: "3"

services: 

  base:
    image: node:alpine
    command: "yarn start"
    volumes:
      - .:/src
    environment:
      DB_HOST: db:3306
      DB_USER: root
      DB_PASSWORD: bins
      DB_DATABASE: bins

  graphql:
    extends:
      service: base
    working_dir: /src/packages/bins-graphql-server
    ports:
      - "4010:4010"
    environment:
      PORT: 4010
    depends_on:
      - db

  worker:
    extends:
      service: base
    working_dir: /src/packages/bins-worker
    ports:
      - "4020:4020"
    environment:
      PORT: 4020
    depends_on:
      - db

  website:
    volumes:
      - .:/src
    image: node:16-alpine
    working_dir: /src/packages/bins-app
    command: "yarn web"
    ports:
      - "4030:19006"
    env_file: ./packages/bins-app/.env

  db:
    image: mariadb:10.5.8
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bins
      MYSQL_DATABASE: bins
      MYSQL_USER: bins
      MYSQL_PASSWORD: bins
    volumes:
      - ./tmp/mysql:/var/lib/mysql
