FROM node:19-alpine as build
ARG APP_NAME

WORKDIR /base
COPY . ./

RUN yarn install --immutable \
    && cd packages/$APP_NAME \
    && npm install -g sharp-cli \
    && yarn build \
    && rm -rf ../../.yarn/cache

FROM nginx:stable-alpine
ARG APP_NAME
COPY --from=build /base/packages/$APP_NAME/web-build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]