name: Build and Publish docker containers
run-name: ${{ gitea.actor }} is running stuff 🚀
on:
  push:
    branches:
    - main
    - "*"
  pull_request:
    branches:
    - main

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to gitea docker
        uses: https://github.com/docker/login-action@v3
        with:
          registry: git2.home.fa.gl
          username: ${{ secrets.PACKIG_USER }}
          password: ${{ secrets.PACKIG_SECRET }}
      - name: Build and push Apt Mirror
        uses: https://github.com/docker/build-push-action@v6
        with:
          file: Dockerfile.web
          push: true
          tags: git2.home.fa.gl/boi/bins-website:latest
          build-args: |
            APP_NAME=bins-app