apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bins-graphql-server-ingress
spec:
  routes:
  - kind: Rule
    match: (Host(`bins.joshbalfour.co.uk`) || Host(`bins.home.fa.gl`)) && PathPrefix(`/api`)
    services:
    - name: bins-graphql-server
      port: 4010
  - kind: Rule
    match: Host(`bins.joshbalfour.co.uk`) || Host(`bins.home.fa.gl`)
    services:
    - name: bins-website
      port: 80
  tls:
    domains:
    - main: bins.home.fa.gl