apiVersion: batch/v1
kind: CronJob
metadata:
  name: bins-worker-next-day-cron
spec:
  schedule: "0 17 * * *"
  successfulJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: git.home.fa.gl/josh/bins-worker:latest
            name: bins-worker
            args: ['index.js', '--next-day']
            command: ['node']
            envFrom:
              - configMapRef:
                  name: bins-cm
              - secretRef:
                  name: db-secret
          restartPolicy: Never